"""preference rank 1-6

Revision ID: 0a49671aa692
Revises: 8b58ea7bf9b3
Create Date: 2026-10-02 19:22:57.249871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a49671aa692'
down_revision: Union[str, None] = '8b58ea7bf9b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
