"""initial schema

Revision ID: 8b58ea7bf9b3
Revises: 
Create Date: 2026-10-02 16:58:08.447246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b58ea7bf9b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('admin_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('branch', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_index(op.f('ix_admins_admin_id'), 'admins', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admins_branch'), 'admins', ['branch'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.String(length=32), nullable=False),
    sa.Column('actor_role', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('entry_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entry_hash'), 'audit_log', ['entry_hash'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_name', sa.String(length=64), nullable=False),
    sa.Column('course_name', sa.String(length=128), nullable=False),
    sa.Column('syllabus_pdf', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actor_id', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('total_students', sa.Integer(), nullable=False),
    sa.Column('first_choice_pct', sa.Float(), nullable=False),
    sa.Column('fifth_choice_pct', sa.Float(), nullable=False),
    sa.Column('fallback_pct', sa.Float(), nullable=False),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('cramers_v', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipient_uid', sa.String(length=32), nullable=True),
    sa.Column('branch', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_branch'), 'notifications', ['branch'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_uid'), 'notifications', ['recipient_uid'], unique=False)
    op.create_table('students',
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('cgpa', sa.Float(), nullable=False),
    sa.Column('contact_no', sa.String(length=20), nullable=False),
    sa.Column('parent_branch', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_students_parent_branch'), 'students', ['parent_branch'], unique=False)
    op.create_index(op.f('ix_students_uid'), 'students', ['uid'], unique=False)
    op.create_table('allotments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_uid', sa.String(length=32), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('branch', sa.String(length=64), nullable=False),
    sa.Column('choice_number', sa.Integer(), nullable=True),
    sa.Column('allotted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_uid'], ['students.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allotments_branch'), 'allotments', ['branch'], unique=False)
    op.create_index(op.f('ix_allotments_course_id'), 'allotments', ['course_id'], unique=False)
    op.create_index(op.f('ix_allotments_student_uid'), 'allotments', ['student_uid'], unique=True)
    op.create_table('course_seats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('branch', sa.String(length=64), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('filled_seats', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'branch', name='uq_course_branch')
    )
    op.create_index(op.f('ix_course_seats_branch'), 'course_seats', ['branch'], unique=False)
    op.create_index(op.f('ix_course_seats_course_id'), 'course_seats', ['course_id'], unique=False)
    op.create_table('preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_uid', sa.String(length=32), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_uid'], ['students.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_uid', 'course_id', name='uq_student_course'),
    sa.UniqueConstraint('student_uid', 'rank', name='uq_student_rank')
    )
    op.create_index(op.f('ix_preferences_course_id'), 'preferences', ['course_id'], unique=False)
    op.create_index(op.f('ix_preferences_student_uid'), 'preferences', ['student_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preferences_student_uid'), table_name='preferences')
    op.drop_index(op.f('ix_preferences_course_id'), table_name='preferences')
    op.drop_table('preferences')
    op.drop_index(op.f('ix_course_seats_course_id'), table_name='course_seats')
    op.drop_index(op.f('ix_course_seats_branch'), table_name='course_seats')
    op.drop_table('course_seats')
    op.drop_index(op.f('ix_allotments_student_uid'), table_name='allotments')
    op.drop_index(op.f('ix_allotments_course_id'), table_name='allotments')
    op.drop_index(op.f('ix_allotments_branch'), table_name='allotments')
    op.drop_table('allotments')
    op.drop_index(op.f('ix_students_uid'), table_name='students')
    op.drop_index(op.f('ix_students_parent_branch'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_notifications_recipient_uid'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_branch'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('experiments')
    op.drop_table('courses')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entry_hash'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_admins_branch'), table_name='admins')
    op.drop_index(op.f('ix_admins_admin_id'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
